import { Nav } from "@/components/nav";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="flex flex-col min-h-full emerald">
			<body
				style={{ textRendering: "optimizeLegibility" }}
				className={cn(
					"grow bg-background font-sans antialiased px-12 w-[min(100%,720px)] mx-auto",
					"font-family text-clamped tracking-tightest"
				)}
			>
				<Nav />
				{children}
			</body>
		</html>
	);
}
