import "@/app/globals.css";
import { Footer } from "@/components/footer";
import { Nav } from "@/components/nav";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function BlogLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="flex flex-col min-h-full emerald">
			<body
				style={{ textRendering: "optimizeLegibility" }}
				className={cn(
					"flex flex-col grow bg-background font-sans antialiased px-[1.5em] w-[min(100%,34.5em)] mx-auto text-clamped"
				)}
			>
				<Nav />
				{children}
				<Footer />
			</body>
		</html>
	);
}
