import "@/app/globals.css";
import "@/app/mdx.css";
import { Footer } from "@/components/footer";
import { Nav } from "@/components/nav";

import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const clearFaceFont = localFont({
	variable: "--font-clearface",
	src: [
		{
			path: "../../../fonts/clearface-regular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "../../../fonts/clearface-italic.ttf",
			weight: "400",
			style: "italic",
		},
		{
			path: "../../../fonts/clearface-bold.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "../../../fonts/clearface-bold-italic.ttf",
			weight: "700",
			style: "italic",
		},
	],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function BlogLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="flex flex-col min-h-full emerald">
			<body
				style={{ textRendering: "optimizeLegibility" }}
				className={cn(
					"flex flex-col grow bg-background font-sans antialiased px-[1.5em] w-[min(100%,34.5em)] mx-auto text-clamped",
					clearFaceFont.variable
				)}
			>
				<Nav />
				{children}
				<Footer />
			</body>
		</html>
	);
}
